// services/seeders/salesMasterSeeder.js
const db = require("../../database/index");
const SaleMaster = db.SaleMaster;
const Ledger = db.Ledger;

async function seedSalesMasters(sequelize, userCompanyId, transaction) {
  const now = new Date();
  console.log(`🌱 Seeding Sale Masters start.............. ${userCompanyId}`);

  const ledgers = await Ledger.findAll({
    where: { companyId: userCompanyId, isDefault: true },
    transaction,
  });

  if (!ledgers || ledgers.length === 0) {
    console.log(
      "⚠️ No default ledgers found for this company. Skipping Sale Master seeding.",
      ledgers
    );
    return;
  }

  const findLedger = (name) => {
    const ledger = ledgers.find((l) =>
      l.ledgerName.toLowerCase().includes(name.toLowerCase())
    );
    return ledger ? ledger.id : ledgers[0]?.id;
  };

  const salesLedgerId = findLedger("sales");
  const igstOutputLedgerId = findLedger("igst output");
  const cgstOutputLedgerId = findLedger("cgst output");
  const sgstOutputLedgerId = findLedger("sgst output");
  const cessOutputLedgerId = findLedger("cess");

  const defaultSaleMasters = [
    {
      salesType: "GST Sale - 12%",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 12.0,
      cgstPercentage: 6.0,
      sgstPercentage: 6.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Taxable",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 1,
      status: "Active",
      description: "GST Sale with 12% tax rate",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST Sale - 18%",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 18.0,
      cgstPercentage: 9.0,
      sgstPercentage: 9.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Taxable",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 2,
      status: "Active",
      description: "GST Sale with 18% tax rate",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST Sale - 28%",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 28.0,
      cgstPercentage: 14.0,
      sgstPercentage: 14.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Taxable",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 3,
      status: "Active",
      description: "GST Sale with 28% tax rate",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST Sale - 5%",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 5.0,
      cgstPercentage: 2.5,
      sgstPercentage: 2.5,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Taxable",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 4,
      status: "Active",
      description: "GST Sale with 5% tax rate",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST Sale - 6%",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 6.0,
      cgstPercentage: 3.0,
      sgstPercentage: 3.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Taxable",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 5,
      status: "Active",
      description: "GST Sale with 6% tax rate",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST Sale Tax Free",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 0.0,
      cgstPercentage: 0.0,
      sgstPercentage: 0.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Exempted",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 6,
      status: "Active",
      description: "GST Sale Tax Free",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST Sale Tax Paid",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 0.0,
      cgstPercentage: 0.0,
      sgstPercentage: 0.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Taxable",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 7,
      status: "Active",
      description: "GST Sale Tax Paid",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST Sale-Exempt",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 0.0,
      cgstPercentage: 0.0,
      sgstPercentage: 0.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Exempted",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 8,
      status: "Active",
      description: "GST Sale Exempt",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST Sale-Nil Rated",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 0.0,
      cgstPercentage: 0.0,
      sgstPercentage: 0.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Nil Rated",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 9,
      status: "Active",
      description: "GST Sale Nil Rated",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST-Deemed Export (Exempted)",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 0.0,
      cgstPercentage: 0.0,
      sgstPercentage: 0.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Exempted",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 10,
      status: "Active",
      description: "GST Deemed Export (Exempted)",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST-Export (Zero Rated)",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 0.0,
      cgstPercentage: 0.0,
      sgstPercentage: 0.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Zero Rated",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 11,
      status: "Active",
      description: "GST Export (Zero Rated)",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST-Sale SEZ (Exempted)",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 0.0,
      cgstPercentage: 0.0,
      sgstPercentage: 0.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Exempted",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 12,
      status: "Active",
      description: "GST Sale SEZ (Exempted)",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST-Sale Ung.Dealer",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 0.0,
      cgstPercentage: 0.0,
      sgstPercentage: 0.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Taxable",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 13,
      status: "Active",
      description: "GST Sale Unregistered Dealer",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "GST-StockTrf -Out (Exempt)",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 0.0,
      cgstPercentage: 0.0,
      sgstPercentage: 0.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Exempted",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 14,
      status: "Active",
      description: "GST Stock Transfer Out (Exempt)",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      salesType: "Item wise",
      localSalesLedgerId: salesLedgerId,
      centralSalesLedgerId: salesLedgerId,
      igstPercentage: 0.0,
      cgstPercentage: 0.0,
      sgstPercentage: 0.0,
      cessPercentage: 0.0,
      natureOfTransaction: "Sales",
      taxability: "Taxable",
      igstLedgerId: igstOutputLedgerId,
      cgstLedgerId: cgstOutputLedgerId,
      sgstLedgerId: sgstOutputLedgerId,
      cessLedgerId: cessOutputLedgerId,
      isActive: true,
      sortOrder: 15,
      status: "Active",
      description: "Item wise GST calculation",
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  const defaultSaleMastersWithCompanyId = defaultSaleMasters.map((master) => ({
    ...master,
    companyId: userCompanyId,
  }));

  await SaleMaster.bulkCreate(defaultSaleMastersWithCompanyId, { transaction });
  console.log(
    `🌱 Seeded ${defaultSaleMastersWithCompanyId.length} Sale Masters for company ${userCompanyId}`
  );
}

module.exports = seedSalesMasters;
