const defaultLedgers = [
  {
    ledgerName: "Capital Account",
    groupName: "Capital Account",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 1,
  },
  {
    ledgerName: "Drawings",
    groupName: "Capital Account",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 2,
  },
  {
    ledgerName: "Cash",
    groupName: "Cash-in-Hand",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 3,
  },
  {
    ledgerName: "Bank Account",
    groupName: "Bank Accounts",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description", "address"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 4,
  },
  {
    ledgerName: "Sales",
    groupName: "Sales Accounts",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 5,
  },
  {
    ledgerName: "Purchase",
    groupName: "Purchase Accounts",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 6,
  },
  {
    ledgerName: "Salaries",
    groupName: "Indirect Expense",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 7,
  },
  {
    ledgerName: "Rent Paid",
    groupName: "Indirect Expense",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 8,
  },
  {
    ledgerName: "Telephone Expenses",
    groupName: "Indirect Expense",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 9,
  },
  {
    ledgerName: "Electricity Charges",
    groupName: "Indirect Expense",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 10,
  },
  {
    ledgerName: "Commission Received",
    groupName: "Indirect Income",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 11,
  },
  {
    ledgerName: "Discount Received",
    groupName: "Indirect Income",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 12,
  },
  {
    ledgerName: "CGST Input",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 13,
  },
  {
    ledgerName: "SGST Input",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 14,
  },
  {
    ledgerName: "IGST Input",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 15,
  },
  {
    ledgerName: "CGST Input (RCM)",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 16,
  },
  {
    ledgerName: "SGST Input (RCM)",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 17,
  },
  {
    ledgerName: "IGST Input (RCM)",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 18,
  },
  {
    ledgerName: "CGST Output",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 19,
  },
  {
    ledgerName: "SGST Output",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 20,
  },
  {
    ledgerName: "IGST Output",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 21,
  },
  {
    ledgerName: "Sundry Debtors",
    groupName: "Sundry Debtors",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description", "address"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 22,
  },
  {
    ledgerName: "Sundry Creditors",
    groupName: "Sundry Creditors",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description", "address"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 23,
  },
  {
    ledgerName: "Sales Return",
    groupName: "Sales Accounts",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 24,
  },
  {
    ledgerName: "Purchase Return",
    groupName: "Purchase Accounts",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 25,
  },
  {
    ledgerName: "Loan from Bank",
    groupName: "Secured Loans",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 26,
  },
  {
    ledgerName: "Loan from Friends",
    groupName: "Unsecured Loans",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 27,
  },
  {
    ledgerName: "Depreciation",
    groupName: "Indirect Expense",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 28,
  },
  {
    ledgerName: "Income Tax",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 29,
  },
  {
    ledgerName: "TDS Receivable",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 30,
  },
  {
    ledgerName: "TDS Payable",
    groupName: "Duties & Taxes",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 31,
  },
  {
    ledgerName: "Advance to Staff",
    groupName: "Loans & Advances (Asset)",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description", "address"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 32,
  },
  {
    ledgerName: "Interest Received",
    groupName: "Indirect Income",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 33,
  },
  {
    ledgerName: "Interest Paid",
    groupName: "Indirect Expense",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Debit",
    isActive: true,
    status: "Active",
    sortOrder: 34,
  },
  {
    ledgerName: "Rounding Off",
    groupName: "Indirect Income",
    isDefault: true,
    isEditable: true,
    isDeletable: false,
    editableFields: JSON.stringify(["openingBalance", "balanceType", "description"]),
    openingBalance: 0.0,
    balance: 0.0,
    balanceType: "Credit",
    isActive: true,
    status: "Active",
    sortOrder: 35,
  },
];

module.exports = defaultLedgers;
